### ISSUE TITLE
更新了Botan1.11之后无法编译的问题

### ISSUE THREAD

**Issue by nnnewb** [slackwarecn-slackbuilds/libqtshadowsocks#1]
```
ln -s /usr/lib64/pkgconfig/botan-1.11.pc /usr/lib64/pkgconfig/botan-1.10.pc
ln -s /usr/lib64/libbotan-1.11.a /usr/lib64/libbotan-1.10.a
ln -s /usr/lib64/libbotan-1.11.so /usr/lib64/libbotan-1.10.so
```

botan的release note里啥都没写，所以只能猜测没有breaking change，如果有需要在这个环境下编译的话只要执行上面几条命令伪造出botan1.10的假象就好了。

建议在libqtshadowsocks官方没有支持之前继续用botan1.10，不要升级，就这样。

**Comment by liuxueyang** [comment]
現在已經支持 Botan-2 了，需要在 `cmake` 的編譯選項裏面加上 `-DUSE_BOTAN2=ON`。
參見 [Compiling](https://github.com/shadowsocks/libQtShadowsocks/wiki/Compiling)
